-- MySQL Script generated by MySQL Workbench
-- Mon May 22 08:46:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema model
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema model
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `model` DEFAULT CHARACTER SET utf8 ;
USE `model` ;


-- //<user>
-- -----------------------------------------------------
-- Table `model`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
-- //<newsletter>
  `subscriber` INT NULL DEFAULT 0,
  -- //</newsletter>
  `number` VARCHAR(45) NULL,
  `address` VARCHAR(350) NULL,
  `lastname` VARCHAR(90) NOT NULL,
  `firstname` VARCHAR(90) NOT NULL,
  `password` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

-- //<album>
-- -----------------------------------------------------
-- Table `model`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model`.`albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `details` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_albums_ users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_albums_ users`
    FOREIGN KEY (`users_id`)
    REFERENCES `model`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `model`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(45) NOT NULL,
  `albums_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE,
  INDEX `fk_image_albums1_idx` (`albums_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_albums1`
    FOREIGN KEY (`albums_id`)
    REFERENCES `model`.`albums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- //</album>
-- //</user>
-- //<contact>
-- -----------------------------------------------------
-- Table `model`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `model`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` INT NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `details` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = INNODB;
-- //</contact>


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
